server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always # SpringBoot 로그를 색상으로 출력해준다. IDEA Ultimate에선 기본으로 동작한다.

    profiles:
      active: dev

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # create는 재시작할 때 테이블을 지우고 다시 만든다 / update는 테이블을 한 번 만들고, 재시작해도 지우진 않는다
    show-sql: false # spring.jpa.properties.show_sql에서 설정했으면 이 부분은 지우거나 false로 설정하는게 좋다
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect # org.hibernate.dialect.MySQLDialect을 사용하면 MySQL 방언 방식과 H2 충돌나는 부분 있음 / 현재는 지워도 크게 상관없는 옵션이다
        format_sql: true # 쿼리를 보기 좋게 포맷팅
        highlight_sql: true # 문법 구분
        use_sql_comments: true # 추가적인 주석 표시 (jpql 정보)
        show_sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.blind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
