server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always # SpringBoot 로그를 색상으로 출력해준다. IDEA Ultimate에선 기본으로 동작한다.

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # create는 재시작할 때 테이블을 지우고 다시 만든다. update는 테이블을 한 번 만들고, 재시작해도 지우진 않는다.
    show-sql: true #
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true